# Banco de dados #
info:
  name: podce-adm

url.db: jdbc:postgresql://localhost:5432/postgres
user.db: postgres
password.db: postgres
min.pool.db: 5
max.pool.db: 30
timeout.db: 10000

dialect.db: org.hibernate.dialect.PostgreSQL9Dialect
data.source.db: org.postgresql.ds.PGSimpleDataSource
hbm2dll: none

spring:
  profiles:
    active: dev
  security:
    user:
      name: eureka
      password: admin
      roles: SYSTEM
  servlet:
    multipart:
      enabled:true
      file-size-threshold:2KB
      max-file-size:7MB
      max-request-size:10MB

server:
  port: 8083
  servlet:
    context-path: /podce-adm

service:
  defaultMinMs: 100
  defaultMaxMs: 200
