info:
  name: podce-adm

spring:
  profiles:
    active: dev
  security:
    user:
      name: eureka
      password: admin
      roles: SYSTEM
  mail:
    debug: true
    host: @mail.host@
    port: @mail.port@
    username: @mail.username@
    password: @mail.password@
    properties:
      mail:
        transport:
          protocol: @mail.protocol@
        smtps:
          auth: true
        smtp:
          starttls:
            enable: true
          ssl:
            enable: false
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: @dll.auto@
  datasource:
    url: @url.db@
    username: @user.db@
    password: @password.db@
    max-pool-size: @max.pool.db@
    min-pool-size: @min.pool.db@
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled:true
      file-size-threshold:2KB
      max-file-size:7MB
      max-request-size:10MB

server:
  port: @podce-adm-port@
  servlet:
    context-path: /podce-adm

service:
  defaultMinMs: 100
  defaultMaxMs: 200

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    lease-expiration-duration-in-seconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761}/eureka/

logging:
  file: @log.path@${info.name}.log
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE